apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-aws
spec:
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.0.0/16
  podSelector:
    matchExpressions:
    - key: k8s-app
      operator: DoesNotExist
